In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv")
df

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.0500,74.4000,0.1
1,2021-01-03 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.0500,74.4000,4.4
2,2021-01-04 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.0500,74.4000,2.3
3,2021-01-05 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.0500,74.4000,35.0
4,2021-01-06 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.0500,74.4000,25.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970334,2025-02-06 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,27.3,22.0,34.0,7.6,1011.4,5,17.7167,83.2333,0.0
970335,2025-02-07 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.7,23.0,30.0,7.7,1013.1,5,17.7167,83.2333,0.3
970336,2025-02-08 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.7,1013.0,5,17.7167,83.2333,0.0
970337,2025-02-09 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.5,1012.8,5,17.7167,83.2333,0.0
970338,2025-02-10 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.5,21.8,31.0,8.2,1013.9,5,17.7167,83.2333,0.0

In [3]:
import pandas as pd

missing_counts = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

missing_summary.sort_values("missing_percent", ascending=False)

                missing_count  missing_percent
air_pressure           304664        31.397687
wind_speed             274444        28.283311
rainfall               257554        26.542683
max_temp               110598        11.397872
min_temp                43898         4.523986
date_of_record              0         0.000000
month                       0         0.000000
season                      0         0.000000
station_name                0         0.000000
state                       0         0.000000
district                    0         0.000000
avg_temp                    0         0.000000
elevation                   0         0.000000
latitude                    0         0.000000
longitude                   0         0.000000

In [4]:
df = df.dropna(subset=["rainfall"])

In [5]:
weather_cols = ["avg_temp", "min_temp", "max_temp", "wind_speed", "air_pressure"]

df = df.sort_values(["station_name", "date_of_record"])

df[weather_cols] = df.groupby("station_name")[weather_cols].transform(
    lambda x: x.interpolate(method="linear").ffill().bfill()
)
df

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
381449,2015-01-02 00:00:00,January,Winter,Agartala,TR,West Tripura,23.1,18.600000,30.3,2.6,1014.8,15,23.8833,91.2500,0.0
381464,2015-01-17 00:00:00,January,Winter,Agartala,TR,West Tripura,20.4,18.593333,27.4,2.6,1014.8,15,23.8833,91.2500,0.3
381465,2015-01-18 00:00:00,January,Winter,Agartala,TR,West Tripura,15.8,18.586667,17.0,2.6,1014.8,15,23.8833,91.2500,2.0
381466,2015-01-19 00:00:00,January,Winter,Agartala,TR,West Tripura,15.2,18.580000,17.7,2.6,1014.8,15,23.8833,91.2500,0.0
381493,2015-02-15 00:00:00,February,Winter,Agartala,TR,West Tripura,19.7,18.573333,27.0,2.6,1014.8,15,23.8833,91.2500,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846112,2025-02-06 00:00:00,February,Winter,Yercaud,TN,Salem,16.7,11.000000,24.0,9.1,1012.6,1463,11.7500,78.1667,0.0
846113,2025-02-07 00:00:00,February,Winter,Yercaud,TN,Salem,17.2,11.800000,24.6,8.8,1013.8,1463,11.7500,78.1667,0.0
846114,2025-02-08 00:00:00,February,Winter,Yercaud,TN,Salem,17.5,12.400000,24.3,9.6,1013.9,1463,11.7500,78.1667,0.0
846115,2025-02-09 00:00:00,February,Winter,Yercaud,TN,Salem,17.7,12.400000,24.3,10.8,1013.4,1463,11.7500,78.1667,0.0
846116,2025-02-10 00:00:00,February,Winter,Yercaud,TN,Salem,17.2,12.100000,24.3,9.8,1014.3,1463,11.7500,78.1667,0.0

In [6]:
import pandas as pd

missing_counts = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

missing_summary.sort_values("missing_percent", ascending=False)

                missing_count  missing_percent
date_of_record              0              0.0
month                       0              0.0
season                      0              0.0
station_name                0              0.0
state                       0              0.0
district                    0              0.0
avg_temp                    0              0.0
min_temp                    0              0.0
max_temp                    0              0.0
wind_speed                  0              0.0
air_pressure                0              0.0
elevation                   0              0.0
latitude                    0              0.0
longitude                   0              0.0
rainfall                    0              0.0

In [7]:
df["temp_k"] = df["avg_temp"] + 273.15
df["pressure_pa"] = df["air_pressure"] * 100

R = 287
df["air_density"] = df["pressure_pa"] / (R * df["temp_k"])
df[["temp_k", "pressure_pa", "air_density"]]

        temp_k  pressure_pa  air_density
381449  296.25     101480.0     1.193549
381464  293.55     101480.0     1.204527
381465  288.95     101480.0     1.223703
381466  288.35     101480.0     1.226249
381493  292.85     101480.0     1.207406
...        ...          ...          ...
846112  289.85     101260.0     1.217258
846113  290.35     101380.0     1.216602
846114  290.65     101390.0     1.215466
846115  290.85     101340.0     1.214031
846116  290.35     101430.0     1.217202

[712785 rows x 3 columns]

In [8]:
df["lat_rad"] = np.radians(df["latitude"])

df["u_velocity"] = df["wind_speed"] * np.cos(df["lat_rad"])
df["v_velocity"] = df["wind_speed"] * np.sin(df["lat_rad"])
df[["u_velocity", "v_velocity", "lat_rad"]]

        u_velocity  v_velocity   lat_rad
381449    2.377367    1.052675  0.416842
381464    2.377367    1.052675  0.416842
381465    2.377367    1.052675  0.416842
381466    2.377367    1.052675  0.416842
381493    2.377367    1.052675  0.416842
...            ...         ...       ...
846112    8.909314    1.853140  0.205076
846113    8.615600    1.792047  0.205076
846114    9.398837    1.954961  0.205076
846115   10.573691    2.199331  0.205076
846116    9.594646    1.995689  0.205076

[712785 rows x 3 columns]

In [9]:
df["pressure_gradient"] = df.groupby("station_name")["air_pressure"].diff().fillna(0)
df["pressure_gradient"]

381449    0.0
381464    0.0
381465    0.0
381466    0.0
381493    0.0
         ...
846112   -0.2
846113    1.2
846114    0.1
846115   -0.5
846116    0.9
Name: pressure_gradient, Length: 712785, dtype: float64

In [10]:
df

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,...,latitude,longitude,rainfall,temp_k,pressure_pa,air_density,lat_rad,u_velocity,v_velocity,pressure_gradient
381449,2015-01-02 00:00:00,January,Winter,Agartala,TR,West Tripura,23.1,18.600000,30.3,2.6,...,23.8833,91.2500,0.0,296.25,101480.0,1.193549,0.416842,2.377367,1.052675,0.0
381464,2015-01-17 00:00:00,January,Winter,Agartala,TR,West Tripura,20.4,18.593333,27.4,2.6,...,23.8833,91.2500,0.3,293.55,101480.0,1.204527,0.416842,2.377367,1.052675,0.0
381465,2015-01-18 00:00:00,January,Winter,Agartala,TR,West Tripura,15.8,18.586667,17.0,2.6,...,23.8833,91.2500,2.0,288.95,101480.0,1.223703,0.416842,2.377367,1.052675,0.0
381466,2015-01-19 00:00:00,January,Winter,Agartala,TR,West Tripura,15.2,18.580000,17.7,2.6,...,23.8833,91.2500,0.0,288.35,101480.0,1.226249,0.416842,2.377367,1.052675,0.0
381493,2015-02-15 00:00:00,February,Winter,Agartala,TR,West Tripura,19.7,18.573333,27.0,2.6,...,23.8833,91.2500,2.0,292.85,101480.0,1.207406,0.416842,2.377367,1.052675,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846112,2025-02-06 00:00:00,February,Winter,Yercaud,TN,Salem,16.7,11.000000,24.0,9.1,...,11.7500,78.1667,0.0,289.85,101260.0,1.217258,0.205076,8.909314,1.853140,-0.2
846113,2025-02-07 00:00:00,February,Winter,Yercaud,TN,Salem,17.2,11.800000,24.6,8.8,...,11.7500,78.1667,0.0,290.35,101380.0,1.216602,0.205076,8.615600,1.792047,1.2
846114,2025-02-08 00:00:00,February,Winter,Yercaud,TN,Salem,17.5,12.400000,24.3,9.6,...,11.7500,78.1667,0.0,290.65,101390.0,1.215466,0.205076,9.398837,1.954961,0.1
846115,2025-02-09 00:00:00,February,Winter,Yercaud,TN,Salem,17.7,12.400000,24.3,10.8,...,11.7500,78.1667,0.0,290.85,101340.0,1.214031,0.205076,10.573691,2.199331,-0.5
846116,2025-02-10 00:00:00,February,Winter,Yercaud,TN,Salem,17.2,12.100000,24.3,9.8,...,11.7500,78.1667,0.0,290.35,101430.0,1.217202,0.205076,9.594646,1.995689,0.9

In [11]:
df["du_dx"] = df.groupby("station_name")["u_velocity"].diff().fillna(0)
df["dv_dy"] = df.groupby("station_name")["v_velocity"].diff().fillna(0)

df["divergence"] = df["du_dx"] + df["dv_dy"]
df[["du_dx", "dv_dy", "divergence"]]

           du_dx     dv_dy  divergence
381449  0.000000  0.000000    0.000000
381464  0.000000  0.000000    0.000000
381465  0.000000  0.000000    0.000000
381466  0.000000  0.000000    0.000000
381493  0.000000  0.000000    0.000000
...          ...       ...         ...
846112  0.587427  0.122185    0.709612
846113 -0.293714 -0.061093   -0.354806
846114  0.783236  0.162913    0.946150
846115  1.174855  0.244370    1.419225
846116 -0.979045 -0.203642   -1.182687

[712785 rows x 3 columns]

In [12]:
df["dv_dx"] = df.groupby("station_name")["v_velocity"].diff().fillna(0)
df["du_dy"] = df.groupby("station_name")["u_velocity"].diff().fillna(0)

df["vorticity"] = df["dv_dx"] - df["du_dy"]
df['vorticity']

381449    0.000000
381464    0.000000
381465    0.000000
381466    0.000000
381493    0.000000
            ...
846112   -0.465242
846113    0.232621
846114   -0.620323
846115   -0.930484
846116    0.775404
Name: vorticity, Length: 712785, dtype: float64

In [13]:
omega = 7.2921e-5

df["coriolis"] = 2 * omega * np.sin(df["lat_rad"])
df[["lat_rad", "coriolis"]]

         lat_rad  coriolis
381449  0.416842  0.000059
381464  0.416842  0.000059
381465  0.416842  0.000059
381466  0.416842  0.000059
381493  0.416842  0.000059
...          ...       ...
846112  0.205076  0.000030
846113  0.205076  0.000030
846114  0.205076  0.000030
846115  0.205076  0.000030
846116  0.205076  0.000030

[712785 rows x 2 columns]

In [14]:
df["kinetic_energy"] = 0.5 * df["air_density"] * (df["wind_speed"]**2)
df[["air_density", "wind_speed", "kinetic_energy"]]

        air_density  wind_speed  kinetic_energy
381449     1.193549         2.6        4.034195
381464     1.204527         2.6        4.071301
381465     1.223703         2.6        4.136115
381466     1.226249         2.6        4.144721
381493     1.207406         2.6        4.081032
...             ...         ...             ...
846112     1.217258         9.1       50.400577
846113     1.216602         8.8       47.106833
846114     1.215466         9.6       56.008684
846115     1.214031        10.8       70.802314
846116     1.217202         9.8       58.450046

[712785 rows x 3 columns]

In [15]:
df["temp_gradient"] = df.groupby("station_name")["avg_temp"].diff().fillna(0)
df[["avg_temp", "temp_gradient"]]

        avg_temp  temp_gradient
381449      23.1            0.0
381464      20.4           -2.7
381465      15.8           -4.6
381466      15.2           -0.6
381493      19.7            4.5
...          ...            ...
846112      16.7           -0.9
846113      17.2            0.5
846114      17.5            0.3
846115      17.7            0.2
846116      17.2           -0.5

[712785 rows x 2 columns]

In [16]:
df["rain_lag_1"] = df.groupby("station_name")["rainfall"].shift(1).fillna(0)
df["rain_lag_3"] = df.groupby("station_name")["rainfall"].shift(3).fillna(0)
df["rain_lag_7"] = df.groupby("station_name")["rainfall"].shift(7).fillna(0)
df["rain_lag_30"] = df.groupby("station_name")["rainfall"].shift(30).fillna(0)
df[["rainfall", "rain_lag_1", "rain_lag_3", "rain_lag_7", "rain_lag_30"]]

        rainfall  rain_lag_1  rain_lag_3  rain_lag_7  rain_lag_30
381449       0.0         0.0         0.0         0.0          0.0
381464       0.3         0.0         0.0         0.0          0.0
381465       2.0         0.3         0.0         0.0          0.0
381466       0.0         2.0         0.0         0.0          0.0
381493       2.0         0.0         0.3         0.0          0.0
...          ...         ...         ...         ...          ...
846112       0.0         0.0         0.0         0.4          1.1
846113       0.0         0.0         0.0         1.1          0.0
846114       0.0         0.0         0.0         0.3          0.0
846115       0.0         0.0         0.0         0.0          0.4
846116       0.0         0.0         0.0         0.0          0.0

[712785 rows x 5 columns]

In [17]:
df["date_of_record"] = pd.to_datetime(df["date_of_record"], errors="coerce")
df["month"] = df["date_of_record"].dt.month

df["month_sin"] = np.sin(2*np.pi*df["month"]/12)
df["month_cos"] = np.cos(2*np.pi*df["month"]/12)
df[["month", "month_sin", "month_cos"]]

        month  month_sin  month_cos
381449      1   0.500000   0.866025
381464      1   0.500000   0.866025
381465      1   0.500000   0.866025
381466      1   0.500000   0.866025
381493      2   0.866025   0.500000
...       ...        ...        ...
846112      2   0.866025   0.500000
846113      2   0.866025   0.500000
846114      2   0.866025   0.500000
846115      2   0.866025   0.500000
846116      2   0.866025   0.500000

[712785 rows x 3 columns]

In [18]:
import pandas as pd

missing_counts = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "missing_count": missing_counts,
    "missing_percent": missing_percent
})

missing_summary.sort_values("missing_percent", ascending=False)

                   missing_count  missing_percent
date_of_record                 0              0.0
u_velocity                     0              0.0
pressure_gradient              0              0.0
du_dx                          0              0.0
dv_dy                          0              0.0
divergence                     0              0.0
dv_dx                          0              0.0
du_dy                          0              0.0
vorticity                      0              0.0
coriolis                       0              0.0
kinetic_energy                 0              0.0
temp_gradient                  0              0.0
rain_lag_1                     0              0.0
rain_lag_3                     0              0.0
rain_lag_7                     0              0.0
rain_lag_30                    0              0.0
month_sin                      0              0.0
v_velocity                     0              0.0
lat_rad                        0              0.0
month                          0              0.0
air_density                    0              0.0
season                         0              0.0
station_name                   0              0.0
state                          0              0.0
district                       0              0.0
avg_temp                       0              0.0
min_temp                       0              0.0
max_temp                       0              0.0
wind_speed                     0              0.0
air_pressure                   0              0.0
elevation                      0              0.0
latitude                       0              0.0
longitude                      0              0.0
rainfall                       0              0.0
temp_k                         0              0.0
pressure_pa                    0              0.0
month_cos                      0              0.0

In [19]:
df.to_csv("processed_weather_data.csv", index=False)

In [20]:
import pandas as pd
df = pd.read_csv("processed_weather_data.csv")
df["date_of_record"] = pd.to_datetime(df["date_of_record"])

print("Stations:", df["station_name"].nunique())
print("Date range:", df["date_of_record"].min(), "→", df["date_of_record"].max())
print("\nRainfall stats per station (mean daily mm):")
print(df.groupby("station_name")["rainfall"].mean().describe())
print("\nColumns:", df.columns.tolist())
print("\nSample rows:", df.shape)

Stations: 406
Date range: 2015-01-01 00:00:00 → 2025-02-10 00:00:00

Rainfall stats per station (mean daily mm):
count    406.000000
mean       4.941546
std        2.935451
min        0.729416
25%        3.095721
50%        4.051230
75%        5.741633
max       24.763419
Name: rainfall, dtype: float64

Columns: ['date_of_record', 'month', 'season', 'station_name', 'state', 'district', 'avg_temp', 'min_temp', 'max_temp', 'wind_speed', 'air_pressure', 'elevation', 'latitude', 'longitude', 'rainfall', 'temp_k', 'pressure_pa', 'air_density', 'lat_rad', 'u_velocity', 'v_velocity', 'pressure_gradient', 'du_dx', 'dv_dy', 'divergence', 'dv_dx', 'du_dy', 'vorticity', 'coriolis', 'kinetic_energy', 'temp_gradient', 'rain_lag_1', 'rain_lag_3', 'rain_lag_7', 'rain_lag_30', 'month_sin', 'month_cos']

Sample rows: (712785, 37)

In [21]:
import pandas as pd
df = pd.read_csv("processed_weather_data.csv")

In [23]:
df.head(20)

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,...,vorticity,coriolis,kinetic_energy,temp_gradient,rain_lag_1,rain_lag_3,rain_lag_7,rain_lag_30,month_sin,month_cos
0,2015-01-02,1,Winter,Agartala,TR,West Tripura,23.1,18.600000,30.30,2.6,...,0.0,0.000059,4.034195,0.0,0.0,0.0,0.0,0.0,0.500000,8.660254e-01
1,2015-01-17,1,Winter,Agartala,TR,West Tripura,20.4,18.593333,27.40,2.6,...,0.0,0.000059,4.071301,-2.7,0.0,0.0,0.0,0.0,0.500000,8.660254e-01
2,2015-01-18,1,Winter,Agartala,TR,West Tripura,15.8,18.586667,17.00,2.6,...,0.0,0.000059,4.136115,-4.6,0.3,0.0,0.0,0.0,0.500000,8.660254e-01
3,2015-01-19,1,Winter,Agartala,TR,West Tripura,15.2,18.580000,17.70,2.6,...,0.0,0.000059,4.144721,-0.6,2.0,0.0,0.0,0.0,0.500000,8.660254e-01
4,2015-02-15,2,Winter,Agartala,TR,West Tripura,19.7,18.573333,27.00,2.6,...,0.0,0.000059,4.081032,4.5,0.0,0.3,0.0,0.0,0.866025,5.000000e-01
5,2015-02-16,2,Winter,Agartala,TR,West Tripura,19.9,18.566667,29.30,2.6,...,0.0,0.000059,4.078247,0.2,2.0,2.0,0.0,0.0,0.866025,5.000000e-01
6,2015-02-19,2,Winter,Agartala,TR,West Tripura,20.0,18.560000,26.50,2.6,...,0.0,0.000059,4.076856,0.1,0.0,0.0,0.0,0.0,0.866025,5.000000e-01
7,2015-02-20,2,Winter,Agartala,TR,West Tripura,21.9,18.553333,28.70,2.6,...,0.0,0.000059,4.050603,1.9,26.9,2.0,0.0,0.0,0.866025,5.000000e-01
8,2015-02-21,2,Winter,Agartala,TR,West Tripura,23.3,18.546667,30.20,2.6,...,0.0,0.000059,4.031473,1.4,2.0,0.0,0.3,0.0,0.866025,5.000000e-01
9,2015-03-04,3,Winter,Agartala,TR,West Tripura,20.4,18.540000,24.50,2.6,...,0.0,0.000059,4.071301,-2.9,0.0,26.9,2.0,0.0,1.000000,6.123234e-17
10,2015-03-05,3,Winter,Agartala,TR,West Tripura,21.4,18.533333,26.80,2.6,...,0.0,0.000059,4.057479,1.0,1.0,2.0,0.0,0.0,1.000000,6.123234e-17
11,2015-03-06,3,Winter,Agartala,TR,West Tripura,20.8,18.526667,29.10,2.6,...,0.0,0.000059,4.065761,-0.6,13.0,0.0,2.0,0.0,1.000000,6.123234e-17
12,2015-03-18,3,Winter,Agartala,TR,West Tripura,25.7,18.520000,34.20,2.6,...,0.0,0.000059,3.999098,4.9,0.0,1.0,0.0,0.0,1.000000,6.123234e-17
13,2015-03-19,3,Winter,Agartala,TR,West Tripura,24.8,18.513333,32.00,2.6,...,0.0,0.000059,4.011177,-0.9,0.0,13.0,26.9,0.0,1.000000,6.123234e-17
14,2015-03-28,3,Winter,Agartala,TR,West Tripura,27.8,18.506667,33.80,2.6,...,0.0,0.000059,3.971192,3.0,0.0,0.0,2.0,0.0,1.000000,6.123234e-17
15,2015-04-02,4,Summer,Agartala,TR,West Tripura,24.7,18.500000,33.40,2.6,...,0.0,0.000059,4.012524,-3.1,0.0,0.0,0.0,0.0,0.866025,-5.000000e-01
16,2015-04-03,4,Summer,Agartala,TR,West Tripura,24.0,18.400000,32.50,2.6,...,0.0,0.000059,4.021976,-0.7,51.1,0.0,1.0,0.0,0.866025,-5.000000e-01
17,2015-04-04,4,Summer,Agartala,TR,West Tripura,26.9,18.500000,33.70,2.6,...,0.0,0.000059,3.983104,2.9,34.0,0.0,13.0,0.0,0.866025,-5.000000e-01
18,2015-04-05,4,Summer,Agartala,TR,West Tripura,23.5,18.600000,31.95,2.6,...,0.0,0.000059,4.028755,-3.4,24.9,51.1,0.0,0.0,0.866025,-5.000000e-01
19,2015-04-06,4,Summer,Agartala,TR,West Tripura,24.6,19.000000,30.20,2.6,...,0.0,0.000059,4.013872,1.1,0.0,34.0,0.0,0.0,0.866025,-5.000000e-01